### ISSUE TITLE
Reunião para definição de milestones 01/09(Quinta-Feira)

### ISSUE THREAD

**Issue by MarlonJhow** [MarlonJhow/TRM6#12]

**Comment by MarlonJhow** [comment]
Seguinte galera,

Milestones são os marcos com as datas das entregas. 

Então teremos que definir os milestones de acordo com o calendario academico e jogamos todas as tarefas para concluir até o prazo daquele milestones. Assim os pré requisitos do projeto de acordo com a normativa e as datas que precisam ser entregues.

**Comment by caggianoneto** [comment]
6h
